# Generated by Django 2.2.28 on 2024-02-28 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamefolio_app.Author'),
        ),
        migrations.AlterField(
            model_name='listentry',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamefolio_app.Game'),
        ),
        migrations.AlterField(
            model_name='listentry',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamefolio_app.List'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamefolio_app.Game'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamefolio_app.Author'),
        ),
    ]
