# Generated by Django 2.2.28 on 2024-02-28 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0002_auto_20240228_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='gameId',
            new_name='game',
        ),
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 0, 25, 17, 575132)),
        ),
    ]
