# Generated by Django 2.2.28 on 2024-02-28 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0003_auto_20240228_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 0, 34, 11, 586628)),
        ),
    ]
