# Generated by Django 2.2.28 on 2024-02-28 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0004_auto_20240228_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 0, 39, 53, 23936, tzinfo=utc)),
        ),
    ]
