# Generated by Django 2.2.28 on 2024-03-20 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0005_auto_20240319_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 11, 40, 54, 349842)),
        ),
    ]
