# Generated by Django 2.2.28 on 2024-03-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0005_auto_20240319_1958'),
        ('gamefolio_app', '0004_auto_20240320_2028'),
    ]

    operations = [
    ]
