# Generated by Django 2.2.28 on 2024-02-28 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0005_auto_20240228_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 0, 40, 13, 890738, tzinfo=utc)),
        ),
    ]
