# Generated by Django 2.2.28 on 2024-03-20 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0006_auto_20240320_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 12, 15, 50, 335435)),
        ),
    ]
