# Generated by Django 2.2.28 on 2024-02-28 02:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0008_auto_20240228_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 2, 15, 58, 585822, tzinfo=utc)),
        ),
    ]
