# Generated by Django 2.2.28 on 2024-03-02 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0009_auto_20240228_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listentry',
            options={'verbose_name_plural': 'List Entries'},
        ),
        migrations.RenameField(
            model_name='list',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(default='defaultprofile.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 13, 56, 36, 829976)),
        ),
    ]
