# Generated by Django 2.2.28 on 2024-02-28 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0009_auto_20240228_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listentry',
            options={'verbose_name_plural': 'List Entries'},
        ),
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(default='defaultprofile.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 14, 30, 0, 239845)),
        ),
    ]
