# Generated by Django 2.2.28 on 2024-03-03 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0010_auto_20240302_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 3, 14, 35, 38, 751205)),
        ),
    ]
