# Generated by Django 2.2.28 on 2024-03-20 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0010_auto_20240320_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 15, 40, 28, 682317)),
        ),
    ]
