# Generated by Django 2.2.28 on 2024-03-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0011_auto_20240303_1435'),
        ('gamefolio_app', '0011_auto_20240302_2244'),
    ]

    operations = [
    ]
