# Generated by Django 2.2.28 on 2024-03-20 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0011_auto_20240320_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 20, 20, 4, 747102)),
        ),
    ]
