# Generated by Django 2.2.28 on 2024-03-08 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0012_merge_20240307_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 15, 14, 41, 614714)),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Ratings'), (1, '½'), (2, '★'), (3, '★½'), (4, '★★'), (5, '★★½'), (6, '★★★'), (7, '★★★½'), (8, '★★★★'), (9, '★★★★½'), (10, '★★★★★')]),
        ),
        migrations.AlterModelTable(
            name='game',
            table='game',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
