# Generated by Django 2.2.28 on 2024-03-09 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0012_merge_20240309_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 17, 45, 9, 962297)),
        ),
    ]
