# Generated by Django 2.2.28 on 2024-03-21 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0012_auto_20240320_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 12, 2, 26, 863639)),
        ),
    ]
