# Generated by Django 2.2.28 on 2024-03-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0004_auto_20240320_2028'),
        ('gamefolio_app', '0013_auto_20240321_1202'),
    ]

    operations = [
    ]
