# Generated by Django 2.2.28 on 2024-03-08 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0013_auto_20240308_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 15, 23, 2, 760240)),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(db_column='game', on_delete=django.db.models.deletion.CASCADE, to='gamefolio_app.Game'),
        ),
    ]
