# Generated by Django 2.2.28 on 2024-03-13 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0013_auto_20240313_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 17, 22, 41, 754911)),
        ),
    ]
