# Generated by Django 2.2.28 on 2024-03-21 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0014_merge_20240321_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 12, 35, 14, 752964)),
        ),
    ]
