# Generated by Django 2.2.28 on 2024-03-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0015_auto_20240321_1235'),
        ('gamefolio_app', '0006_merge_20240321_1047'),
    ]

    operations = [
    ]
